In [1]:
import pandas as pd
import pyobo

data_url = "../ARI List of Autoimmune Diseases 2026.csv"
#df = pd.read_csv(data_url, names=["Category","Evidence","Quality","autoimmune","Parent","Disease","Syn","SNOMED","ConceptID"], header=0)
df = pd.read_csv(data_url, header=0)
#df = df[["species", "strain", "organ"]]

/home/agar/.venvs/biomap_venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
mondo_grounder = pyobo.get_grounder("mondo", force = True, cache = True)
uberon_grounder = pyobo.get_grounder("uberon", force = True, cache = True)
cl_grounder = pyobo.get_grounder("cl", force = True, cache = True)
doid_grounder = pyobo.get_grounder("doid", force = True, cache = True)

#BUG - failed Pydantic validation for some reason, but the grounder is working fine. {WARNING:pyobo.struct.obo.reader:[doid:9352] failed Pydantic validation KEGG:04930 in xref}

[mondo] parsing OBO: 882kit [00:03, 276kit/s]
WARNING:pyobo.struct.reference:[obo:mondo - dcterms:source] couldn't parse IRI http://www.orpha.net/ontology/orphanet.owl in property object in terms:source http://www.orpha.net/ontology/orphanet.owl
WARNING:pyobo.struct.reference:[obo:mondo - dcterms:source] couldn't parse IRI https://id.nlm.nih.gov/mesh in property object in terms:source https://id.nlm.nih.gov/mesh/
WARNING:pyobo.struct.reference:[obo:mondo - dcterms:source] couldn't parse IRI https://rarediseases.info.nih.gov in property object in terms:source https://rarediseases.info.nih.gov/
WARNING:pyobo.struct.obo.reader:[ro:0002503] failed to parse definition quotes: no closing quote found in `q towards e2 if and only if q is a relational quality such that q inheres-in some e, and e`
[mondo]:  21%|██▏       | 12.4k/58.4k [00:01<00:04, 10.4kit/s]WARNING:pyobo.struct.reference:[mondo:0000030] failed Pydantic validation MONDO:patterns/hereditary in definition provenance in "An instance of sleep-related hypermotor epilepsy that is caused by an inherited genomic modification in an individual." [MONDO:patterns/hereditary]
WARNING:pyobo.struct.reference:[mondo:0000044] failed Pydantic validation MONDO:patterns/hereditary in synonym provenance in "hereditary hypophosphatemic rickets" EXACT [MONDO:patterns/hereditary]
WARNING:pyobo.struct.reference:[mondo:0000062] failed Pydantic validation MONDO:patterns/isolated in synonym provenance in "nonsyndromic microphthalmia" EXACT [MONDO:patterns/isolated]
WARNING:pyobo.struct.reference:[mondo:0000062] failed Pydantic validation MONDO:patterns/isolated in definition provenance in "A microphthalmia that is not part of a larger syndrome." [MONDO:patterns/isolated]
WARNING:pyobo.struct.reference:[mondo:0000063] failed Pydantic validation MONDO:ambiguous in synonym provenance in "molybdenum cofactor deficiency" EXACT [MONDO:ambiguous]
WARNING:pyobo.struct.reference:[mondo:0000065 - dcterms:conformsTo] unregistered prefix in inherited:susceptibility.yaml in property object in terms:conformsTo inherited:susceptibility.yaml
WARNING:pyobo.struct.reference:[mondo:0000075 - iao:0000231] failed Pydantic validation MONDO:TermsMerged in property object in IAO:0000231 MONDO:TermsMerged
WARNING:pyobo.struct.reference:[mondo:0000155] failed Pydantic validation MONDO:patterns/inborn_metabolic in synonym provenance in "inborn error of sequestering of triglyceride" EXACT [MONDO:patterns/inborn_metabolic]
WARNING:pyobo.struct.reference:[mondo:0000155 - dcterms:conformsTo] unregistered prefix in inborn:metabolic.yaml in property object in terms:conformsTo inborn:metabolic.yaml
WARNING:pyobo.struct.reference:[mondo:0000155] failed Pydantic validation MONDO:patterns/inborn_metabolic in definition provenance in "An inherited metabolic disease that is has its basis in the disruption of sequestering of triglyceride." [MONDO:patterns/inborn_metabolic]
WARNING:pyobo.struct.obo.reader:[mondo:0000163 - iao:0000233] failed Pydantic validation https://github.com/monarch-initiative/mondo/pull/6628 in property object in IAO:0000233 "https://github.com/monarch-initiative/mondo/pull/6628" xsd:anyURI
WARNING:pyobo.struct.reference:[mondo:0000170] failed Pydantic validation MONDO:Lexical in synonym provenance in "MCOPCB1" RELATED ABBREVIATION [MONDO:Lexical]
WARNING:pyobo.struct.reference:[mondo:0000200] failed Pydantic validation MONDO:RULE_1 in synonym provenance in "Zimmermann-Laband syndrome type 1" EXACT [MONDO:RULE_1]
WARNING:pyobo.struct.reference:[mondo:0000212] failed Pydantic validation MONDO:design_pattern in synonym provenance in "autosomal recessive hypercalcemia, infantile" EXACT [MONDO:design_pattern]
WARNING:pyobo.struct.reference:[mondo:0000212] failed Pydantic validation MONDO:patterns/infantile in synonym provenance in "hypercalcemia disease of infancy" EXACT [MONDO:design_pattern, MONDO:patterns/infantile]
WARNING:pyobo.struct.reference:[mondo:0000212] failed Pydantic validation MONDO:patterns/autosomal_recessive in synonym provenance in "hypercalcemia, infantile, autosomal recessive" EXACT [MONDO:design_pattern, MONDO:patterns/autosomal_recessive]
WARNING:pyobo.struct.reference:[mondo:0000212] failed Pydantic validation MONDO:design_pattern in definition provenance in "A hypercalcemia disease that occurs between 28 days to one year of life." [MONDO:design_pattern]
WARNING:pyobo.struct.reference:[mondo:0000222] failed Pydantic validation MONDO:patterns/acute in synonym provenance in "acute gonococcal seminal vesiculitis" EXACT [icd11.foundation:477968215, MONDO:patterns/acute]
WARNING:pyobo.struct.reference:[mondo:0000222] failed Pydantic validation MONDO:patterns/acute in definition provenance in "Acute form of gonococcal seminal vesiculitis." [MONDO:patterns/acute]
WARNING:pyobo.struct.reference:[mondo:0000236] failed Pydantic validation MONDO:patterns/location in synonym provenance in "oropharynx anthrax infection" EXACT [MONDO:patterns/location]
WARNING:pyobo.struct.reference:[mondo:0000236] failed Pydantic validation MONDO:patterns/location in definition provenance in "A anthrax infection that involves the oropharynx." [MONDO:patterns/location]
WARNING:pyobo.struct.reference:[mondo:0000252] failed Pydantic validation MONDO:patterns/specific_inflammatory_disease_by_site in definition provenance in "An diarrhea (disease) involving a pathogenic inflammatory response in the intestinal mucosa." [MONDO:patterns/specific_inflammatory_disease_by_site]
WARNING:pyobo.struct.reference:[mondo:0000261] failed Pydantic validation MONDO:patterns/inflammatory_disease_by_site in synonym provenance in "pharyngeal tonsil inflammation" EXACT [MONDO:patterns/inflammatory_disease_by_site]
WARNING:pyobo.struct.reference:[mondo:0000261] failed Pydantic validation MONDO:patterns/inflammatory_disease_by_site in definition provenance in "An inflammatory disease involving a pathogenic inflammatory response in the pharyngeal tonsil." [MONDO:patterns/inflammatory_disease_by_site]
WARNING:pyobo.struct.reference:[mondo:0000263] failed Pydantic validation MONDO:patterns in definition provenance in "An inflammation of both larynx and trachea." [MONDO:patterns]
WARNING:pyobo.struct.reference:[mondo:0000270] failed Pydantic validation MONDO:patterns/location_top in synonym provenance in "disease of lower respiratory tract" EXACT [MONDO:patterns/location_top]
WARNING:pyobo.struct.reference:[mondo:0000270 - dcterms:conformsTo] unregistered prefix in location:top.yaml in property object in terms:conformsTo location:top.yaml
WARNING:pyobo.struct.reference:[mondo:0000276] failed Pydantic validation MONDO:patterns/specific_infectious_disease_by_agent in synonym provenance in "Powassan virus caused disease or disorder" EXACT [MONDO:patterns/specific_infectious_disease_by_agent]
WARNING:pyobo.struct.reference:[mondo:0000276] failed Pydantic validation MONDO:patterns/infectious_disease_by_agent in definition provenance in "A disease caused by infection with Powassan virus." [MONDO:patterns/infectious_disease_by_agent]
WARNING:pyobo.struct.reference:[mondo:0000290] failed Pydantic validation MONDO:patterns/infectious_disease_by_agent in synonym provenance in "infections, Naegleria fowleri" RELATED [MONDO:patterns/infectious_disease_by_agent]
WARNING:pyobo.struct.reference:[mondo:0000294] failed Pydantic validation MONDO:patterns/specific_infectious_disease_by_agent in definition provenance in "An disease or disorder caused by infection with Mesocestoides." [MONDO:patterns/specific_infectious_disease_by_agent]
WARNING:pyobo.struct.reference:[mondo:0000308 - dcterms:conformsTo] unregistered prefix in primary:infectious.yaml in property object in terms:conformsTo primary:infectious.yaml
WARNING:pyobo.struct.reference:[mondo:0000371] failed Pydantic validation MONDO:patterns/carcinoma_in_situ in synonym provenance in "carcinoma in situ of oral cavity" EXACT [icd11.foundation:1389868484, MONDO:patterns/carcinoma_in_situ, NCIT:C4587]
WARNING:pyobo.struct.reference:[mondo:0000373] failed Pydantic validation MONDO:patterns/carcinoma_in_situ in definition provenance in "A carcinoma in situ involving a gall bladder." [MONDO:patterns/carcinoma_in_situ]
WARNING:pyobo.struct.reference:[mondo:0000376] failed Pydantic validation MONDO:patterns/cancer in synonym provenance in "cancer of respiratory system" EXACT [MONDO:patterns/cancer]
WARNING:pyobo.struct.reference:[mondo:0000377] failed Pydantic validation MONDO:patterns/malignant in synonym provenance in "Leydig cell tumor, malignant" EXACT [MONDO:patterns/malignant, NCIT:C4213]
WARNING:pyobo.struct.reference:[mondo:0000379] failed Pydantic validation MONDO:patterns/malignant in definition provenance in "A malignant form of Sertoli-leydig cell tumor." [MONDO:patterns/malignant]
WARNING:pyobo.struct.reference:[mondo:0000380] failed Pydantic validation MONDO:patterns/carcinoma in synonym provenance in "carcinoma of paranasal sinus" EXACT [DOID:0050619, MONDO:patterns/carcinoma, NCIT:C6014]
WARNING:pyobo.struct.reference:[mondo:0000382 - dcterms:conformsTo] unregistered prefix in benign:neoplasm.yaml in property object in terms:conformsTo benign:neoplasm.yaml
WARNING:pyobo.struct.reference:[mondo:0000411] failed Pydantic validation http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3267655/table/T1 in definition provenance in "OBSOLETE. An epilepsy syndrome that is a group of clinical entities showing a cluster of electro-clinical characteristics, classified according to age at onset, cognitive and developmental antecedents and consequences, motor and sensory examinations, EEG features, provoking or triggering factors, and patterns of seizure occurrence with respect to sleep." [DOID:0050701, http://www.ice-epilepsy.org/new-ice-terminology-from-ilae.html, http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3267655/table/T1/, PMID:20196795]
WARNING:pyobo.struct.reference:[mondo:0000414] failed Pydantic validation MONDO:patterns/childhood in synonym provenance in "electroclinical syndrome of childhood" EXACT [MONDO:design_pattern, MONDO:patterns/childhood]
WARNING:pyobo.struct.reference:[mondo:0000425] failed Pydantic validation MONDO:patterns/x_linked in synonym provenance in "disease or disorder, X-linked" EXACT [MONDO:patterns/x_linked]
WARNING:pyobo.struct.reference:[mondo:0000425 - dcterms:conformsTo] unregistered prefix in x:linked.yaml in property object in terms:conformsTo x:linked.yaml
WARNING:pyobo.struct.reference:[mondo:0000425] failed Pydantic validation MONDO:patterns/x_linked in definition provenance in "X-linked form of disease." [MONDO:patterns/x_linked]
WARNING:pyobo.struct.reference:[mondo:0000426] failed Pydantic validation MONDO:patterns/autosomal_dominant in synonym provenance in "disease or disorder, autosomal dominant" EXACT [MONDO:patterns/autosomal_dominant]
WARNING:pyobo.struct.reference:[mondo:0000426 - dcterms:conformsTo] unregistered prefix in autosomal:dominant.yaml in property object in terms:conformsTo autosomal:dominant.yaml
WARNING:pyobo.struct.reference:[mondo:0000426] failed Pydantic validation MONDO:patterns/autosomal_dominant in definition provenance in "Autosomal dominant form of disease." [MONDO:patterns/autosomal_dominant]
WARNING:pyobo.struct.reference:[mondo:0000428] failed Pydantic validation MONDO:patterns/y_linked in synonym provenance in "disease or disorder, Y-linked" EXACT [MONDO:patterns/y_linked]
WARNING:pyobo.struct.reference:[mondo:0000428 - dcterms:conformsTo] unregistered prefix in y:linked.yaml in property object in terms:conformsTo y:linked.yaml
WARNING:pyobo.struct.reference:[mondo:0000428] failed Pydantic validation MONDO:patterns/y_linked in definition provenance in "Y-linked form of disease." [MONDO:patterns/y_linked]
[mondo]:  23%|██▎       | 13.5k/58.4k [00:02<00:11, 3.92kit/s]WARNING:pyobo.struct.reference:[mondo:0000462] failed Pydantic validation MONDO:patterns/location_top in definition provenance in "A disease involving the ocular adnexa." [MONDO:patterns/location_top]
WARNING:pyobo.struct.reference:[mondo:0000492] failed Pydantic validation MONDO:patterns/chronic in synonym provenance in "venous insufficiency (disease), chronic" EXACT [MONDO:patterns/chronic]
WARNING:pyobo.struct.reference:[mondo:0000492] failed Pydantic validation MONDO:patterns/chronic in definition provenance in "Chronic form of venous insufficiency (disease)." [MONDO:patterns/chronic]
WARNING:pyobo.struct.reference:[mondo:0000508] failed Pydantic validation MONDO:patterns/syndromic in synonym provenance in "syndrome associated with intellectual disability" EXACT [MONDO:patterns/syndromic]
WARNING:pyobo.struct.reference:[mondo:0000508] failed Pydantic validation MONDO:patterns/syndromic in definition provenance in "A intellectual disability that is part of a larger syndrome." [MONDO:patterns/syndromic]
WARNING:pyobo.struct.obo.reader:[mondo:0000510 - iao:0000233] failed Pydantic validation https://github.com/monarch-initiative/mondo/pull/9599 in property object in IAO:0000233 "https://github.com/monarch-initiative/mondo/pull/9599" xsd:anyURI
WARNING:pyobo.struct.reference:[mondo:0000531 - dcterms:conformsTo] unregistered prefix in mucoepidermoid:carcinoma.yaml in property object in terms:conformsTo mucoepidermoid:carcinoma.yaml
WARNING:pyobo.struct.reference:[mondo:0000540] failed Pydantic validation MONDO:patterns/neuroendocrine_neoplasm_grade1 in synonym provenance in "grade 1 neuroendocrine neoplasm of small intestine" EXACT [MONDO:patterns/neuroendocrine_neoplasm_grade1]
WARNING:pyobo.struct.reference:[mondo:0000577] failed Pydantic validation MONDO:patterns/congenital in synonym provenance in "congenital anemia (disease)" EXACT [MONDO:patterns/congenital]
WARNING:pyobo.struct.reference:[mondo:0000587] failed Pydantic validation MONDO:patterns/autoimmune in definition provenance in "An autoimmune form of otorhinolaryngologic disease." [MONDO:patterns/autoimmune]
WARNING:pyobo.struct.reference:[mondo:0000606] failed Pydantic validation MONDO:patterns/allergy in synonym provenance in "allergy of gluten" EXACT [MONDO:patterns/allergy]
WARNING:pyobo.struct.reference:[mondo:0000606] failed Pydantic validation MONDO:patterns/allergy in definition provenance in "OBSOLETE. A allergy involving gluten." [MONDO:patterns/allergy]
WARNING:pyobo.struct.reference:[mondo:0000639] failed Pydantic validation MONDO:patterns/cancer in definition provenance in "A cancer involving a cartilage tissue." [MONDO:patterns/cancer]
WARNING:pyobo.struct.reference:[mondo:0000654] failed Pydantic validation MONDO:patterns/benign in synonym provenance in "connective and soft tissue neoplasm, benign" EXACT [MONDO:patterns/benign, NCIT:C53684]
WARNING:pyobo.struct.reference:[mondo:0000757 - dcterms:conformsTo] unregistered prefix in environmental:stimulus.yaml in property object in terms:conformsTo environmental:stimulus.yaml
WARNING:pyobo.struct.reference:[mondo:0000764] failed Pydantic validation MONDO:patterns/disease_series_by_gene in synonym provenance in "TGFBI corneal dystrophy (disease)" EXACT [MONDO:patterns/disease_series_by_gene]
WARNING:pyobo.struct.reference:[mondo:0000771] failed Pydantic validation MONDO:patterns/allergic_form_of_disease in synonym provenance in "allergic form of respiratory system disease" EXACT [MONDO:patterns/allergic_form_of_disease]
WARNING:pyobo.struct.reference:[mondo:0000771] failed Pydantic validation MONDO:patterns/allergic_form_of_disease in definition provenance in "A respiratory system disease with a basis in a pathological type I hypersensitivity reaction." [MONDO:patterns/allergic_form_of_disease]
WARNING:pyobo.struct.reference:[mondo:0000814] failed Pydantic validation MONDO:patterns/adult in synonym provenance in "B-cell childhood acute lymphoblastic leukemia of adults" EXACT [MONDO:design_pattern, MONDO:patterns/adult]
WARNING:pyobo.struct.reference:[mondo:0000815] failed Pydantic validation http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2905398 in definition provenance in "A specific developmental disorder that is characterized by physical, behavioral and learning birth defects resulting from maternal ingestion of nicotine during pregnancy." [DOID:0060606, http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2905398/, PMID:20363831]
WARNING:pyobo.struct.reference:[mondo:0000891] failed Pydantic validation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4880064 in definition provenance in "A fibrolamellar carcinoma that is characterized by the presence of both pure fibrolamellar hepatocellular carcinoma and and conventional hepatocellular carcinoma components." [DOID:0080182, https://wjso.biomedcentral.com/articles/10.1186/s12957-016-0903-8, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4880064/]
WARNING:pyobo.struct.reference:[mondo:0000908] failed Pydantic validation MONDO:RULE_2 in synonym provenance in "arrhythmogenic right ventricular dysplasia type 13" EXACT [MONDO:RULE_2]
WARNING:pyobo.struct.reference:[mondo:0000908] failed Pydantic validation MONDO:patterns/disease_series_by_gene in definition provenance in "Any arrhythmogenic right ventricular cardiomyopathy in which the cause of the disease is a mutation in the CTNNA3 gene." [MONDO:patterns/disease_series_by_gene]
WARNING:pyobo.struct.reference:[mondo:0000911] failed Pydantic validation MONDO:RULE_4 in synonym provenance in "cardiomyopathy, dilated, type 1T" EXACT [MONDO:RULE_4]
WARNING:pyobo.struct.reference:[mondo:0000921] failed Pydantic validation MONDO:patterns/neoplasm in synonym provenance in "hepatopancreatic ampulla tumor" EXACT [MONDO:patterns/neoplasm]
WARNING:pyobo.struct.reference:[mondo:0001000] failed Pydantic validation MONDO:patterns/environmental_stimulus in synonym provenance in "mineral dust pneumoconiosis" EXACT [MONDO:patterns/environmental_stimulus]
WARNING:pyobo.struct.reference:[mondo:0001198] failed Pydantic validation MONDO:patterns/acquired in synonym provenance in "acquired thrombocytopenia" EXACT [DOID:11126, icd11.foundation:526155201, MONDO:patterns/acquired]
WARNING:pyobo.struct.reference:[mondo:0001198] failed Pydantic validation MONDO:patterns/acquired in definition provenance in "An instance of thrombocytopenia that is acquired during the lifetime of the individual." [MONDO:patterns/acquired]
WARNING:pyobo.struct.reference:[mondo:0001204] failed Pydantic validation MONDO:patterns/sarcoma in synonym provenance in "sarcoma of esophagus" EXACT [MONDO:patterns/sarcoma, NCIT:C5341]
WARNING:pyobo.struct.reference:[mondo:0001240] failed Pydantic validation MTH:NOCODE in synonym provenance in "anemia neonatal" EXACT [DOID:11244, MTH:NOCODE]
[mondo]:  25%|██▍       | 14.3k/58.4k [00:04<00:34, 1.27kit/s]WARNING:pyobo.struct.reference:[mondo:0001284] failed Pydantic validation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4229526 in definition provenance in "Endometriosis that affects the intesines." [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4229526/]
WARNING:pyobo.struct.reference:[mondo:0001328] failed Pydantic validation MESH:D018382-modified in definition provenance in "An inherited autosomal recessive trait, characterized by peripheral resistance to thyroid hormones and the resulting elevation in serum levels of thyroxine and triiodothyronine." [MESH:D018382-modified]
WARNING:pyobo.struct.reference:[mondo:0001343] failed Pydantic validation MONDO:patterns/disease_by_dysfunctional_structure in synonym provenance in "disease of kidney" BROAD [MONDO:patterns/disease_by_dysfunctional_structure]
WARNING:pyobo.struct.reference:[mondo:0001343] failed Pydantic validation MONDO:patterns/disease_by_dysfunctional_structure in definition provenance in "Any disease in which the causes of the disease is a perturbation of the kidney leading to its dysfunction." [MONDO:patterns/disease_by_dysfunctional_structure]
WARNING:pyobo.struct.reference:[mondo:0001421] failed Pydantic validation MONDO:patterns/neoplasm in definition provenance in "A neoplasm involving a frontal lobe." [MONDO:patterns/neoplasm]

[mondo 2026-03-03] writing names to /home/agar/.data/pyobo/raw/mondo/2026-03-03/cache/names.tsv.gz
[mondo 2026-03-03] writing definitions to /home/agar/.data/pyobo/raw/mondo/2026-03-03/cache/definitions.tsv.gz
[mondo 2026-03-03] writing species to /home/agar/.data/pyobo/raw/mondo/2026-03-03/cache/species.tsv.gz
[mondo 2026-03-03] writing alts to /home/agar/.data/pyobo/raw/mondo/2026-03-03/cache/alt_ids.tsv.gz
[mondo 2026-03-03] writing mappings to /home/agar/.data/pyobo/raw/mondo/2026-03-03/cache/mappings.tsv.gz

WARNING:pyobo.struct.struct:[mondo:0000005] undefined typedef: ReferenceTuple(prefix='iao', identifier='0000233')
WARNING:pyobo.struct.struct:[mondo:0000022] undefined typedef: ReferenceTuple(prefix='obo', identifier='mondo#excluded_from_qc_check')
WARNING:pyobo.struct.struct:[mondo:0000155] undefined typedef: ReferenceTuple(prefix='dcterms', identifier='conformsTo')
WARNING:pyobo.struct.struct:[mondo:0000169] undefined typedef: ReferenceTuple(prefix='iao', identifier='0000231')

[mondo 2026-03-03] writing relations to /home/agar/.data/pyobo/raw/mondo/2026-03-03/cache/relations.tsv.gz
[mondo 2026-03-03] writing edges to /home/agar/.data/pyobo/raw/mondo/2026-03-03/cache/edges.tsv.gz

WARNING:pyobo.struct.struct:[mondo:0005641] undefined typedef: ReferenceTuple(prefix='semapv', identifier='crossSpeciesExactMatch')

[mondo 2026-03-03] writing object_properties to /home/agar/.data/pyobo/raw/mondo/2026-03-03/cache/object_properties.tsv.gz
[mondo 2026-03-03] writing literal_properties to /home/agar/.data/pyobo/raw/mondo/2026-03-03/cache/literal_properties.tsv.gz
[mondo 2026-03-03] writing literal_mappings to /home/agar/.data/pyobo/raw/mondo/2026-03-03/cache/literal_mappings.tsv.gz

[uberon] parsing OBO: 223kit [00:00, 282kit/s]
WARNING:pyobo.struct.reference:[obo:uberon - dc:contributor] failed Pydantic validation https://github.com/orgs/pato-ontology/teams/pato-community in property object in dc-contributor https://github.com/orgs/pato-ontology/teams/pato-community
WARNING:pyobo.struct.reference:[obo:uberon - obo:uberon#dc-source] couldn't parse IRI http://braininfo.rprc.washington.edu in property object in dc-source http://braininfo.rprc.washington.edu/
WARNING:pyobo.struct.reference:[obo:uberon - obo:uberon#dc-source] couldn't parse IRI http://dbpedia.org in property object in dc-source http://dbpedia.org
WARNING:pyobo.struct.reference:[obo:uberon - obo:uberon#dc-source] couldn't parse IRI http://en.wikipedia.org/wiki in property object in dc-source http://en.wikipedia.org/wiki/
WARNING:pyobo.struct.reference:[obo:uberon - obo:uberon#dc-source] couldn't parse IRI http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-GrossAnatomy.owl in property object in dc-source http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-GrossAnatomy.owl
WARNING:pyobo.struct.reference:[obo:uberon - obo:uberon#dc-source] couldn't parse IRI http://palaeos.com in property object in dc-source http://palaeos.com
WARNING:pyobo.struct.reference:[obo:uberon - obo:uberon#dc-source] couldn't parse IRI http://pons.incf.org/wiki/Common_Upper_Mammalian_Brain_Ontology_%28Cumbo%29 in property object in dc-source http://pons.incf.org/wiki/Common_Upper_Mammalian_Brain_Ontology_%28Cumbo%29
WARNING:pyobo.struct.reference:[obo:uberon - obo:uberon#dc-source] couldn't parse IRI http://uri.neuinfo.org/nif/nifstd in property object in dc-source http://uri.neuinfo.org/nif/nifstd
WARNING:pyobo.struct.reference:[obo:uberon - obo:uberon#dc-source] couldn't parse IRI http://www.brain-map.org in property object in dc-source http://www.brain-map.org
WARNING:pyobo.struct.reference:[obo:uberon - obo:uberon#dc-source] couldn't parse IRI http://www.e-lico.eu/public/kupo/kupo.owl in property object in dc-source http://www.e-lico.eu/public/kupo/kupo.owl
WARNING:pyobo.struct.reference:[obo:uberon - obo:uberon#dc-source] failed Pydantic validation http://www.ebi.ac.uk/efo/efo.owl in property object in dc-source http://www.ebi.ac.uk/efo/efo.owl
WARNING:pyobo.struct.obo.reader:[obo:uberon - obo:uberon#doap-bug-database] failed Pydantic validation https://github.com/obophenotype/uberon/issues in property object in doap-bug-database "https://github.com/obophenotype/uberon/issues/" xsd:anyURI
WARNING:pyobo.struct.reference:[ro:0002173 - rdfs:seeAlso] failed Pydantic validation https://github.com/obophenotype/uberon/wiki/Taxon-constraints in property object in seeAlso https://github.com/obophenotype/uberon/wiki/Taxon-constraints
WARNING:pyobo.struct.obo.reader:[ro:0002171 - rdfs:seeAlso] failed Pydantic validation https://github.com/obophenotype/uberon/wiki/Part-disjointness-Design-Pattern in property object in seeAlso "https://github.com/obophenotype/uberon/wiki/Part-disjointness-Design-Pattern" xsd:anyURI
WARNING:pyobo.struct.reference:[bfo:0000050 - rdfs:seeAlso] couldn't parse IRI http://ontologydesignpatterns.org/wiki/Community:Parts_and_Collections in property object in seeAlso http://ontologydesignpatterns.org/wiki/Community:Parts_and_Collections
WARNING:pyobo.struct.reference:[bfo:0000050 - rdfs:seeAlso] couldn't parse IRI http://ontologydesignpatterns.org/wiki/Submissions:PartOf in property object in seeAlso http://ontologydesignpatterns.org/wiki/Submissions:PartOf
[uberon]:   0%|          | 0.00/16.1k [00:00<?, ?it/s]WARNING:pyobo.struct.obo.reader:[uberon:0000000 - rdfs:seeAlso] failed Pydantic validation https://github.com/OBOFoundry/COB/issues/51 in property object in seeAlso "https://github.com/OBOFoundry/COB/issues/51" xsd:anyURI
WARNING:pyobo.struct.reference:[uberon:0000002] failed Pydantic validation FMA:TA in synonym provenance in "canalis cervicis uteri" EXACT OMO:0003011 [FMA:17740, FMA:TA]
WARNING:pyobo.struct.reference:[uberon:0000006] failed Pydantic validation MESH:A03.734.414 in definition provenance in "The clusters of hormone-producing cells that are scattered throughout the pancreas." [MA:0000127, MESH:A03.734.414, MP:0005215]
WARNING:pyobo.struct.reference:[uberon:0000007] failed Pydantic validation ZFIN:curator in definition provenance in "The pituitary gland is an endocrine gland that secretes hormones that regulate many other glands [GO]. An endocrine gland located ventral to the diencephalon and derived from mixed neuroectodermal and non neuroectodermal origin [ZFIN]." [Wikipedia:Pituitary_gland, ZFIN:curator]
WARNING:pyobo.struct.reference:[uberon:0000016] failed Pydantic validation GO:GO in definition provenance in "The part of the pancreas that is part of the endocrine system and is made up of islet cells, which produce insulin, glucagon and somatostatin." [GO:GO, http://orcid.org/0000-0002-6601-2165]
WARNING:pyobo.struct.reference:[uberon:0000017] unregistered prefix in GOC:GO in definition provenance in "The part of the pancreas that is part of the exocrine system and which produces and store zymogens of digestive enzymes, such as chymotrypsinogen and trypsinogen in the acinar cells [GO]." [GOC:GO, http://orcid.org/0000-0002-6601-2165]
WARNING:pyobo.struct.reference:[uberon:0000018] failed Pydantic validation FB:gg in definition provenance in "A light sensing organ composed of ommatidia." [FB:gg, Wikipedia:Compound_eye]
WARNING:pyobo.struct.reference:[uberon:0000026] failed Pydantic validation CARO:DOS in definition provenance in "Major subdivision of an organism that protrudes from the body[DOS, CARO]." [CARO:DOS]
WARNING:pyobo.struct.reference:[uberon:0000035] unregistered prefix in GOC:mtg_mpo in definition provenance in "An ovarian follicle that has one layer of granulosa cells." [GO:0001545, GOC:mtg_mpo, http://ovary.stanford.edu]
WARNING:pyobo.struct.reference:[uberon:0000041] failed Pydantic validation VSAO:curator in synonym provenance in "placoid scale" EXACT [VSAO:curator]
[uberon]:   0%|          | 42.0/16.1k [00:00<00:38, 419it/s]WARNING:pyobo.struct.reference:[uberon:0000053] failed Pydantic validation MESH:A09.371.729.522 in definition provenance in "An oval area in the retina, usually located temporal to the posterior pole of the eye and slightly below the level of the optic disk. It is characterized by the presence of a yellow pigment diffusely permeating the inner layers, contains the fovea centralis in its center, and provides the best phototopic visual acuity. It is devoid of retinal blood vessels, except in its periphery, and receives nourishment from the choriocapillaris of the choroid. (From Cline et al., Dictionary of Visual Science, 4th ed)." [MESH:A09.371.729.522]
WARNING:pyobo.struct.reference:[uberon:0000054] failed Pydantic validation MESH:A09.246.631.909.625.125 in synonym provenance in "acoustic macula" RELATED [MESH:A09.246.631.909.625.125]
WARNING:pyobo.struct.reference:[uberon:0000054] failed Pydantic validation MESH:A09.246.631.909.625.125 in definition provenance in "Thickened areas of the saccule or utricle where the termination of the vestibular nerve occurs[MESH,modified]." [MESH:A09.246.631.909.625.125]
WARNING:pyobo.struct.reference:[uberon:0000057] failed Pydantic validation MGI:anna in definition provenance in "The fibromuscular tubular canal through which urine is discharged from the bladder to the exterior via the external urinary meatus; in males, the urethra is joined by the ejaculatory ducts and serves as a passageway for semen during ejaculation, as well as a canal for urine during voiding; in females, the urethra is shorter and emerges above the vaginal opening." [MGI:anna, MP:0000537]
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in BilaDO:0000004 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in BtauDv:0000078 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in CfamDv:0000007 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in ChirDv:0000014 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in DpseDv:0000005 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in DsimDv:0000005 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in EcabDv:0000007 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in FcatDv:0000007 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in GgalDv:0000076 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in GgorDv:0000032 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in MmulDv:0000052 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in OanaDv:0000007 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in OariDv:0000024 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in PpanDv:0000041 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in PtroDv:0000052 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in RnorDv:0000061 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in SsalDv:0000040 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000066] unregistered prefix in SscrDv:0000084 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in AcarDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in BilaDO:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in BtauDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in CfamDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in ChirDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in CporDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in DpseDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in DsimDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in EcabDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in FcatDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in GgalDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in GgorDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in MdomDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in MmulDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in OanaDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in OariDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in OcunDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in OGES:000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in OGES:000022 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in PpanDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in PtroDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in RnorDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in SsalDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000068] unregistered prefix in SscrDv:0000002 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000069] unregistered prefix in DpseDv:0000003 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000069] unregistered prefix in DsimDv:0000003 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000069] unregistered prefix in OGES:000008 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000069] unregistered prefix in SsalDv:0000039 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000070] unregistered prefix in DpseDv:0000004 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000070] unregistered prefix in DsimDv:0000004 in xref
WARNING:pyobo.struct.reference:[uberon:0000075] unregistered prefix in UBERONREF:0000003 in definition provenance in "Anatomical cluster consisting of the skeletal elements and articular elements that are part of an individual subdivision of the organism." [https://orcid.org/0000-0002-6601-2165, UBERONREF:0000003]
WARNING:pyobo.struct.reference:[uberon:0000080] failed Pydantic validation MESH:A16.254.500 in synonym provenance in "Wolffian body" EXACT [BTO:0001542, GOC:yaf, MESH:A16.254.500, Wikipedia:Mesonephros]
WARNING:pyobo.struct.reference:[uberon:0000087] failed Pydantic validation MGI:pvb in definition provenance in "A mass of cells that develop into the body of the embryo and some extraembryonic tissues." [ISBN:0-683-40008-8, MGI:pvb]
[uberon]:   1%|          | 84.0/16.1k [00:00<00:39, 403it/s]WARNING:pyobo.struct.reference:[uberon:0000089] failed Pydantic validation GO:dph in definition provenance in "Missing definition for term UBERON:0000089. Please replace it using linked reference." [GO:dph, ZFIN:cvs]
WARNING:pyobo.struct.reference:[uberon:0000089] failed Pydantic validation ZFIN:cvs in definition provenance in "Missing definition for term UBERON:0000089. Please replace it using linked reference." [GO:dph, ZFIN:cvs]
WARNING:pyobo.struct.obo.reader:[uberon:0000092] unregistered prefix in BilaDO:0000003 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000092] unregistered prefix in OGES:000010 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000092] unregistered prefix in OGES:000014 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000092] unregistered prefix in OGES:000024 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000092] unregistered prefix in SsalDv:0000038 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in AcarDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in BtauDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in CfamDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in ChirDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in CporDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in DpseDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in DsimDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in EcabDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in FcatDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in GgalDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in GgorDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in MdomDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in MmulDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] failed Pydantic validation ncithesaurus:Life in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in OanaDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in OariDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in OcunDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in OGES:000011 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in PpanDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in PtroDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in RnorDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in SsalDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000104] unregistered prefix in SscrDv:0000001 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in AcarDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in BtauDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in CfamDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in ChirDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in CporDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in DpseDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in DsimDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in EcabDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in FcatDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in GgalDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in GgorDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in MdomDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in MmulDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] failed Pydantic validation ncithesaurus:Developmental_Stage in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in OanaDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in OariDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in OcunDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in PpanDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in PtroDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in RnorDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in SsalDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000105] unregistered prefix in SscrDv:0000000 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000106] unregistered prefix in BilaDO:0000005 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000106] unregistered prefix in ChirDv:0000003 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000106] unregistered prefix in OariDv:0000009 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000106] unregistered prefix in RnorDv:0000048 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000106] unregistered prefix in SsalDv:0000003 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000106] unregistered prefix in SscrDv:0000087 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000107] unregistered prefix in BilaDO:0000006 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000107] unregistered prefix in ChirDv:0000004 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000107] unregistered prefix in GgalDv:0000064 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000107] unregistered prefix in OariDv:0000010 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000107] unregistered prefix in OGES:000015 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000107] unregistered prefix in OGES:000020 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000107] unregistered prefix in RnorDv:0000049 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000107] unregistered prefix in SsalDv:0000004 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000107] unregistered prefix in SscrDv:0000088 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000108] unregistered prefix in BilaDO:0000007 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000108] unregistered prefix in ChirDv:0000010 in xref
WARNING:pyobo.struct.obo.reader:[uberon:0000108] unregistered prefix in GgalDv:0000091 in xref

[uberon 2025-12-04] writing names to /home/agar/.data/pyobo/raw/uberon/2025-12-04/cache/names.tsv.gz
[uberon 2025-12-04] writing definitions to /home/agar/.data/pyobo/raw/uberon/2025-12-04/cache/definitions.tsv.gz
[uberon 2025-12-04] writing species to /home/agar/.data/pyobo/raw/uberon/2025-12-04/cache/species.tsv.gz
[uberon 2025-12-04] writing alts to /home/agar/.data/pyobo/raw/uberon/2025-12-04/cache/alt_ids.tsv.gz
[uberon 2025-12-04] writing mappings to /home/agar/.data/pyobo/raw/uberon/2025-12-04/cache/mappings.tsv.gz
[uberon 2025-12-04] writing relations to /home/agar/.data/pyobo/raw/uberon/2025-12-04/cache/relations.tsv.gz
[uberon 2025-12-04] writing edges to /home/agar/.data/pyobo/raw/uberon/2025-12-04/cache/edges.tsv.gz
[uberon 2025-12-04] writing object_properties to /home/agar/.data/pyobo/raw/uberon/2025-12-04/cache/object_properties.tsv.gz
[uberon 2025-12-04] writing literal_properties to /home/agar/.data/pyobo/raw/uberon/2025-12-04/cache/literal_properties.tsv.gz
[uberon 2025-12-04] writing literal_mappings to /home/agar/.data/pyobo/raw/uberon/2025-12-04/cache/literal_mappings.tsv.gz

[cl] parsing OBO: 304kit [00:01, 275kit/s]
WARNING:pyobo.struct.reference:[bfo:0000050 - rdfs:seeAlso] couldn't parse IRI http://ontologydesignpatterns.org/wiki/Community:Parts_and_Collections in property object in seeAlso http://ontologydesignpatterns.org/wiki/Community:Parts_and_Collections
WARNING:pyobo.struct.reference:[bfo:0000050 - rdfs:seeAlso] couldn't parse IRI http://ontologydesignpatterns.org/wiki/Submissions:PartOf in property object in seeAlso http://ontologydesignpatterns.org/wiki/Submissions:PartOf
WARNING:pyobo.struct.reference:[ro:0002160 - rdfs:seeAlso] failed Pydantic validation https://github.com/obophenotype/uberon/wiki/Taxon-constraints in property object in seeAlso https://github.com/obophenotype/uberon/wiki/Taxon-constraints
WARNING:pyobo.struct.obo.reader:[ro:0002163 - rdfs:seeAlso] failed Pydantic validation https://github.com/obophenotype/uberon/wiki/Part-disjointness-Design-Pattern in property object in seeAlso "https://github.com/obophenotype/uberon/wiki/Part-disjointness-Design-Pattern" xsd:anyURI
WARNING:pyobo.struct.obo.reader:[ro:0002170 - rdfs:seeAlso] failed Pydantic validation https://github.com/obophenotype/uberon/wiki/Connectivity-Design-Pattern in property object in seeAlso "https://github.com/obophenotype/uberon/wiki/Connectivity-Design-Pattern" xsd:anyURI
WARNING:pyobo.struct.obo.reader:[ro:0002170 - rdfs:seeAlso] failed Pydantic validation https://github.com/obophenotype/uberon/wiki/Modeling-articulations-Design-Pattern in property object in seeAlso "https://github.com/obophenotype/uberon/wiki/Modeling-articulations-Design-Pattern" xsd:anyURI
WARNING:pyobo.struct.obo.reader:[ro:0002176 - rdfs:seeAlso] failed Pydantic validation https://github.com/obophenotype/uberon/wiki/Connectivity-Design-Pattern in property object in seeAlso "https://github.com/obophenotype/uberon/wiki/Connectivity-Design-Pattern" xsd:anyURI
WARNING:pyobo.struct.obo.reader:[ro:0002176 - rdfs:seeAlso] failed Pydantic validation https://github.com/obophenotype/uberon/wiki/Modeling-articulations-Design-Pattern in property object in seeAlso "https://github.com/obophenotype/uberon/wiki/Modeling-articulations-Design-Pattern" xsd:anyURI
WARNING:pyobo.struct.reference:[ro:0002180 - rdfs:seeAlso] couldn't parse IRI http://ontologydesignpatterns.org/wiki/Submissions:Componency in property object in seeAlso http://ontologydesignpatterns.org/wiki/Submissions:Componency
WARNING:pyobo.struct.reference:[ro:0002295 - rdfs:seeAlso] unregistered prefix in Ontology:extensions in property object in seeAlso Ontology:extensions
WARNING:pyobo.struct.reference:[ro:0002304 - rdfs:seeAlso] couldn't parse IRI https://wiki.geneontology.org/Causally_upstream_of,_positive_effect in property object in seeAlso https://wiki.geneontology.org/Causally_upstream_of,_positive_effect
WARNING:pyobo.struct.reference:[ro:0002305 - rdfs:seeAlso] couldn't parse IRI https://wiki.geneontology.org/Causally_upstream_of,_negative_effect in property object in seeAlso https://wiki.geneontology.org/Causally_upstream_of,_negative_effect
WARNING:pyobo.struct.reference:[ro:0002387 - rdfs:seeAlso] failed Pydantic validation https://github.com/oborel/obo-relations/issues/810 in property object in seeAlso https://github.com/oborel/obo-relations/issues/810
WARNING:pyobo.struct.reference:[ro:0002563 - rdfs:seeAlso] couldn't parse IRI http://ontologydesignpatterns.org/wiki/Submissions:N-Ary_Relation_Pattern_%28OWL_2%29 in property object in seeAlso http://ontologydesignpatterns.org/wiki/Submissions:N-Ary_Relation_Pattern_%28OWL_2%29
WARNING:pyobo.struct.reference:[ro:0004047 - rdfs:seeAlso] couldn't parse IRI https://wiki.geneontology.org/Causally_upstream_of_or_within,_positive_effect in property object in seeAlso https://wiki.geneontology.org/Causally_upstream_of_or_within,_positive_effect
WARNING:pyobo.struct.obo.reader:[ro:0015003 - iao:0000116] not a CURIE X in property datatype in IAO:0000116 "X subcluster_of Y iff: X and Y are clusters/groups; X
WARNING:pyobo.struct.reference:[ro:0015015 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/1481 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/1481
[cl]:   0%|          | 0.00/19.2k [00:00<?, ?it/s]WARNING:pyobo.struct.reference:[cl:0000000] failed Pydantic validation CARO:mah in definition provenance in "A material entity of anatomical origin (part of or deriving from an organism) that has as its parts a maximally connected cell compartment surrounded by a plasma membrane." [CARO:mah]
WARNING:pyobo.struct.reference:[cl:0000001] failed Pydantic validation ReO:mhb in definition provenance in "A cultured cell that is freshly isolated from a organismal source, or derives in culture from such a cell prior to the culture being passaged." [ReO:mhb]
WARNING:pyobo.struct.reference:[cl:0000003 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/2124 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/2124
WARNING:pyobo.struct.reference:[cl:0000004] failed Pydantic validation FB:ma in definition provenance in "OBSOLETE: A classification of cells by the organisms within which they are contained." [FB:ma]
WARNING:pyobo.struct.obo.reader:[cl:0000015] failed Pydantic validation ncithesaurus:Spermatogenic_Cell in xref
WARNING:pyobo.struct.obo.reader:[cl:0000021] failed Pydantic validation ncithesaurus:Egg in xref
WARNING:pyobo.struct.reference:[cl:0000054 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/2698 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/2698
WARNING:pyobo.struct.reference:[cl:0000055] unregistered prefix in SANBI:mhl in definition provenance in "OBSOLETE. A precursor cell with a limited number of potential fates." [SANBI:mhl]
[cl]:   0%|          | 70.0/19.2k [00:00<00:27, 692it/s]WARNING:pyobo.struct.reference:[cl:0000065] unregistered prefix in JB:jb in definition provenance in "A neuroepithelial glial cell, derived from a radial glial cell originating from the neuroectoderm, lines the ventricles of the brain and the central canal of the spinal cord. This cell is characterized by the presence of cilia on its apical surface, which can be motile or non-motile." [doi:/10.3389/fncel.2021.703951, GOC:tfm, https://www.britannica.com/science/ependymal-cell, JB:jb, PMID:34335193, PMID:37008045, PMID:9550134]
WARNING:pyobo.struct.reference:[cl:0000073 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/1149 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/1149
WARNING:pyobo.struct.reference:[cl:0000085 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/1935 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/1935
WARNING:pyobo.struct.reference:[cl:0000124 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/715 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/715
[cl]:   1%|          | 140/19.2k [00:00<00:27, 682it/s] WARNING:pyobo.struct.reference:[cl:0000161 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/427 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/427
WARNING:pyobo.struct.obo.reader:[cl:0000169] failed Pydantic validation ncithesaurus:Beta_Cell in xref
WARNING:pyobo.struct.reference:[cl:0000181 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/720 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/720
[cl]:   1%|          | 215/19.2k [00:00<00:26, 711it/s]WARNING:pyobo.struct.reference:[cl:0000212 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/2271 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/2271
WARNING:pyobo.struct.reference:[cl:0000212] failed Pydantic validation CL:CVS in definition provenance in "OBSOLETE. A cell that takes up and metabolizes substances." [CL:CVS]
WARNING:pyobo.struct.reference:[cl:0000213 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/3014 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/3014
WARNING:pyobo.struct.reference:[cl:0000215 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/3012 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/3012
WARNING:pyobo.struct.reference:[cl:0000217 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/3013 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/3013
WARNING:pyobo.struct.reference:[cl:0000254] unregistered prefix in TAIR:lr in definition provenance in "Obsolete. Use PO:0020094 from Plant Ontology instead. The female gamete of plants." [TAIR:lr]
WARNING:pyobo.struct.reference:[cl:0000293 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/3010 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/3010
WARNING:pyobo.struct.reference:[cl:0000293] unregistered prefix in TAIR:sr in definition provenance in "OBSOLETE. A cell whose primary function is to provide structural support, to provide strength and physical integrity to the organism." [TAIR:sr]
WARNING:pyobo.struct.obo.reader:[cl:0000354] failed Pydantic validation ncithesaurus:Blastemal_Cell in xref
[cl]:   2%|▏         | 356/19.2k [00:00<00:19, 982it/s]WARNING:pyobo.struct.reference:[cl:0000362] failed Pydantic validation Flybase:dsj in definition provenance in "An epithelial cell of the integument (the outer layer of an organism)." [Flybase:dsj, MA:ma]
WARNING:pyobo.struct.reference:[cl:0000362] failed Pydantic validation MA:ma in definition provenance in "An epithelial cell of the integument (the outer layer of an organism)." [Flybase:dsj, MA:ma]
WARNING:pyobo.struct.reference:[cl:0000381 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/1784 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/1784
WARNING:pyobo.struct.reference:[cl:0000386 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/3016 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/3016
WARNING:pyobo.struct.reference:[cl:0000391 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/1949 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/1949
WARNING:pyobo.struct.reference:[cl:0000402 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/2869 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/2869
WARNING:pyobo.struct.reference:[cl:0000405 - iao:0000233] failed Pydantic validation https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues/1621 in property object in IAO:0000233 https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues/1621
WARNING:pyobo.struct.reference:[cl:0000426 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/708 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/708
WARNING:pyobo.struct.reference:[cl:0000452 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/3161 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/3161
WARNING:pyobo.struct.reference:[cl:0000463] failed Pydantic validation FlyBase:ds in definition provenance in "An epidermal cell that secretes chitinous cuticle from its apical side." [FlyBase:ds, ISBN:ISBN\:978-0801481253]
WARNING:pyobo.struct.reference:[cl:0000463] failed Pydantic validation ISBN:ISBN\:978-0801481253 in definition provenance in "An epidermal cell that secretes chitinous cuticle from its apical side." [FlyBase:ds, ISBN:ISBN\:978-0801481253]
WARNING:pyobo.struct.reference:[cl:0000473 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/pull/3056 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/pull/3056
WARNING:pyobo.struct.reference:[cl:0000478] failed Pydantic validation GO:tfm in definition provenance in "A peptide hormone secreting cell that secretes oxytocin stimulating hormone" [GO:tfm]
WARNING:pyobo.struct.reference:[cl:0000492] unregistered prefix in GOC:pam in definition provenance in "A CD4-positive, alpha-beta T cell that cooperates with other lymphocytes via direct contact or cytokine release to initiate a variety of immune functions." [GO_REF:0000031, GOC:add, GOC:pam, GOC:tfm, ISBN:0781735149, MESH:D006377]
[cl]:   3%|▎         | 487/19.2k [00:00<00:17, 1.10kit/s]WARNING:pyobo.struct.reference:[cl:0000562] unregistered prefix in GOc:tfm in definition provenance in "An erythrocyte having a nucleus." [GOC:add, GOc:tfm]
WARNING:pyobo.struct.reference:[cl:0000583] unregistered prefix in GOC:ana in definition provenance in "A tissue-resident macrophage found in the alveoli of the lungs. Ingests small inhaled particles resulting in degradation and presentation of the antigen to immunocompetent cells. Markers include F4/80-positive, CD11b-/low, CD11c-positive, CD68-positive, sialoadhesin-positive, dectin-1-positive, MR-positive, CX3CR1-negative." [GO_REF:0000031, GOC:ana, GOC:dsd, GOC:tfm, MESH:D016676]
WARNING:pyobo.struct.reference:[cl:0000596] failed Pydantic validation SGD:clt in definition provenance in "A spore formed following meiosis. Sometimes following meiosis, prospores may undergo one or more rounds of mitosis before they are fully mature." [FAO:0000017, GOC:tfm, SGD:clt]
[cl]:   3%|▎         | 597/19.2k [00:00<00:19, 935it/s]  WARNING:pyobo.struct.reference:[cl:0000627 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/2990 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/2990
WARNING:pyobo.struct.reference:[cl:0000644] failed Pydantic validation http://www.neurolex.org/wiki/Category\:Bergmann_Glial_Cell in definition provenance in "Type of radial astrocyte in the cerebellar cortex that have their cell bodies in the Purkinje cell layer and processes that extend into the molecular layer, terminating with bulbous endfeet at the pial surface. Bergmann glia express high densities of glutamate transporters that limit diffusion of the neurotransmitter glutamate during its release from synaptic terminals. Besides their role in early development of the cerebellum, Bergmann glia are also required for the pruning or addition of synapses." [GOC:tfm, http://www.neurolex.org/wiki/Category\:Bergmann_Glial_Cell]
WARNING:pyobo.struct.reference:[cl:0000663 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/726 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/726
WARNING:pyobo.struct.reference:[cl:0000700] unregistered prefix in GOC:dhill in definition provenance in "A neuron that releases dopamine as a neurotransmitter." [GOC:dhill]
[cl]:   4%|▎         | 695/19.2k [00:00<00:20, 905it/s]WARNING:pyobo.struct.reference:[cl:0000717 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/1364 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/1364
WARNING:pyobo.struct.reference:[cl:0000727 - iao:0000233] failed Pydantic validation https://github.com/obophenotype/cell-ontology/issues/1930 in property object in IAO:0000233 https://github.com/obophenotype/cell-ontology/issues/1930
WARNING:pyobo.struct.reference:[cl:0000746] unregistered prefix in GOC:mtg_cardiacconduct_nov11 in definition provenance in "Cardiac muscle cells are striated muscle cells that are responsible for heart contraction. In mammals, the contractile fiber resembles those of skeletal muscle but are only one third as large in diameter, are richer in sarcoplasm, and contain centrally located instead of peripheral nuclei." [GOC:mtg_cardiacconduct_nov11, GOC:tfm, ISBN:0323052908, PMID:22426062, PMID:4711263]
WARNING:pyobo.struct.reference:[cl:0000787] unregistered prefix in GOC:rhs in definition provenance in "A memory B cell is a mature B cell that is long-lived, readily activated upon re-encounter of its antigenic determinant, and has been selected for expression of higher affinity immunoglobulin. This cell type has the phenotype CD19-positive, CD20-positive, MHC Class II-positive, and CD138-negative." [GO_REF:0000031, GOC:add, GOC:dsd, GOC:rhs, http://en.wikipedia.org/wiki/Memory_B_cell, ISBN:0781735149, PMID:20081059, PMID:20839338]
[cl]:   5%|▍         | 875/19.2k [00:01<00:24, 738it/s]WARNING:pyobo.struct.reference:[cl:0000911] unregistered prefix in GOC:PAM-ADD in definition provenance in "A differentiated T cell with ability to traffic to peripheral tissues and is capable of mounting a specific immune response." [GOC:PAM-ADD, GOC:tfm, ISBN:0877799148, PMID:18395547]
WARNING:pyobo.struct.reference:[cl:0000943] unregistered prefix in GOC:msz in definition provenance in "A Be cell that facilitates development of T-helper 1 (Th1) phenotype in CD4-positive T cells, and secretes high levels of interleukin-2, tumor necrosis factor-alpha and interferon-gamma." [GO_REF:0000031, GOC:dsd, GOC:msz, GOC:tfm, PMID:11101868, PMID:20224569]
[cl]:   5%|▌         | 1.02k/19.2k [00:01<00:27, 652it/s]WARNING:pyobo.struct.reference:[cl:0001039] failed Pydantic validation VSAO:curator in definition provenance in "Osteoblast that is terminally differentiated, located adjacent to acellular or cellular bone tissue within periosteum, and is capable of mineralizing the matrix." [VSAO:curator]
WARNING:pyobo.struct.obo.reader:[cl:0001061] couldn't parse IRI https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&code=C12913 in xref
WARNING:pyobo.struct.reference:[cl:0001061] unregistered prefix in GOC:cg in definition provenance in "A cell found in an organism or derived from an organism exhibiting a phenotype that deviates from the expected phenotype of any native cell type of that organism. Abnormal cells are typically found in disease states or disease models." [GOC:add, GOC:cg, GOC:wdd]
WARNING:pyobo.struct.reference:[cl:0001061] unregistered prefix in GOC:wdd in definition provenance in "A cell found in an organism or derived from an organism exhibiting a phenotype that deviates from the expected phenotype of any native cell type of that organism. Abnormal cells are typically found in disease states or disease models." [GOC:add, GOC:cg, GOC:wdd]
WARNING:pyobo.struct.obo.reader:[cl:0001063] couldn't parse IRI https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&code=C12922 in xref
WARNING:pyobo.struct.obo.reader:[cl:0001064] couldn't parse IRI https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&code=C12917 in xref
WARNING:pyobo.struct.reference:[cl:0002000] unregistered prefix in GOC:ak in definition provenance in "An erythroid progenitor cell is Kit-positive, Ly6A-negative, CD41-negative, CD127-negative, and CD123-negative. This cell type is also described as being lin-negative, Kit-positive, CD150-negative, CD41-negative, CD105-positive, and FcgR-negative." [GOC:ak, GOC:tfm, http://www.immgen.org/index_content.html, PMID:19805084]

[cl 2025-12-17] writing names to /home/agar/.data/pyobo/raw/cl/2025-12-17/cache/names.tsv.gz
[cl 2025-12-17] writing definitions to /home/agar/.data/pyobo/raw/cl/2025-12-17/cache/definitions.tsv.gz
[cl 2025-12-17] writing species to /home/agar/.data/pyobo/raw/cl/2025-12-17/cache/species.tsv.gz
[cl 2025-12-17] writing alts to /home/agar/.data/pyobo/raw/cl/2025-12-17/cache/alt_ids.tsv.gz
[cl 2025-12-17] writing mappings to /home/agar/.data/pyobo/raw/cl/2025-12-17/cache/mappings.tsv.gz
[cl 2025-12-17] writing relations to /home/agar/.data/pyobo/raw/cl/2025-12-17/cache/relations.tsv.gz
[cl 2025-12-17] writing edges to /home/agar/.data/pyobo/raw/cl/2025-12-17/cache/edges.tsv.gz
[cl 2025-12-17] writing object_properties to /home/agar/.data/pyobo/raw/cl/2025-12-17/cache/object_properties.tsv.gz
[cl 2025-12-17] writing literal_properties to /home/agar/.data/pyobo/raw/cl/2025-12-17/cache/literal_properties.tsv.gz
[cl 2025-12-17] writing literal_mappings to /home/agar/.data/pyobo/raw/cl/2025-12-17/cache/literal_mappings.tsv.gz

[doid] parsing OBO: 165kit [00:00, 310kit/s]
[doid]:   0%|          | 0.00/14.5k [00:00<?, ?it/s]WARNING:pyobo.struct.reference:[doid:0040104] failed Pydantic validation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3194110 in definition provenance in "A toluene meta-diisocyanate allergic asthma that has_allergic_trigger toluene 2,4-diisocyanate." [url:https\://www.ncbi.nlm.nih.gov/pmc/articles/PMC3194110/]
[doid]:   1%|▏         | 197/14.5k [00:00<00:07, 1.97kit/s]WARNING:pyobo.struct.reference:[doid:0050169] failed Pydantic validation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3927537 in definition provenance in "A lupus erythematosus that causes skin lesions on parts of the body that are exposed to sunlight." [url:https\://www.ncbi.nlm.nih.gov/pmc/articles/PMC3927537/]
WARNING:pyobo.struct.reference:[doid:0050178] failed Pydantic validation DO:wk in definition provenance in "A genetic disease that require multiple abnormal alleles to manifest are complex. These diseases are termed multifactorial or polygenic. Expressivity or penetrance of the disease is complex and is associated with multiple genes in combination with lifestyle and environmental factors. Multifactoral genetic diseases include heart disease and diabetes, although a subset of diabetes may be classified as a monogenic disease (due to the presence of a single abnormal allele)." [DO:wk]
WARNING:pyobo.struct.obo.reader:[doid:0050192] unregistered prefix in SNOMEDCT_US_2025_05_01:721791005 in xref
WARNING:pyobo.struct.reference:[doid:0050194] failed Pydantic validation http://www.jstor.org/stable/30129873?seq=1 in definition provenance in "A viral infectious disease that is a hemorrhagic fever, has_material_basis_in Junin virus (Mammarenavirus juninense), which is transmitted_by rodent, Calomys musculinus. The infection has_symptom fever, has_symptom fatigue, has_symptom malaise, has_symptom leukopenia, has_symptom thrombocytopenia, and has_symptom hemorrhagic manifestations." [url:http\://en.wikipedia.org/wiki/Argentine_hemorrhagic_fever, url:http\://www.jstor.org/stable/30129873?seq=1]
WARNING:pyobo.struct.obo.reader:[doid:0050202] unregistered prefix in SNOMEDCT_US_2025_05_01:716585008 in xref
WARNING:pyobo.struct.reference:[doid:0050236] failed Pydantic validation http://tolweb.org/Heterolobosea/96360 in definition provenance in "A parasitic protozoa infectious disease that involves infection caused by the members of the class Heterolobosea, which move with eruptive bulges and show transformation to a temporary flagellate stage." [url:http\://tolweb.org/Heterolobosea/96360]
WARNING:pyobo.struct.reference:[doid:0050239] failed Pydantic validation http://tolweb.org/Fornicata/121182 in definition provenance in "A parasitic protozoa infectious disease that involves infection caused by fornicates, which are unicellular flagellates with one or two karyomastigonts per cell." [url:http\://tolweb.org/Fornicata/121182]
[doid]:   3%|▎         | 439/14.5k [00:00<00:06, 2.23kit/s]WARNING:pyobo.struct.obo.reader:[doid:0050508] unregistered prefix in SNOMEDCT_US_2025_05_01:47452006 in xref
WARNING:pyobo.struct.obo.reader:[doid:0050516] unregistered prefix in SNOMEDCT_US_2025_05_01:85579005 in xref
WARNING:pyobo.struct.obo.reader:[doid:0050524] failed Pydantic validation KEGG:04950 in xref
WARNING:pyobo.struct.obo.reader:[doid:0050524] unregistered prefix in SNOMEDCT_US_2025_05_01:609561005 in xref
WARNING:pyobo.struct.reference:[doid:0050534] failed Pydantic validation http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1772254 in definition provenance in "A hereditary night blindness that is characterized by hemeralopia with a moderate loss of visual acuity and caused by defective photoreceptor-to-bipolar cell signaling with common ERG findings of reduced or absent b-waves and generally normal a-waves." [url:http\://disorders.eyes.arizona.edu/disorders/night-blindness-congenital-stationary-csnbad3, url:http\://www.ncbi.nlm.nih.gov/books/NBK1245/, url:http\://www.ncbi.nlm.nih.gov/pmc/articles/PMC1772254/, url:http\://www.omim.org/entry/610444, url:http\://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=215]
WARNING:pyobo.struct.reference:[doid:0050537] failed Pydantic validation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3729648 in definition provenance in "A cataract that is characterized by a distinctive discoid lens opacity situated posteriorly and adjacent to the posterior capsule." [url:https\://www.ncbi.nlm.nih.gov/pmc/articles/PMC3729648/]
WARNING:pyobo.struct.reference:[doid:0050548] failed Pydantic validation http://omim.org/entry/616488?search=616488&highlight=616488 in definition provenance in "A neuropathy characterized by congenital insensitivity to pain resulting in ulceration to the fingers, tongue, lips, and other distal appendages." [url:http\://omim.org/entry/616488?search=616488&highlight=616488]
WARNING:pyobo.struct.obo.reader:[doid:0050589] failed Pydantic validation KEGG:05321 in xref
WARNING:pyobo.struct.reference:[doid:0050623] failed Pydantic validation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1398414 in definition provenance in "A urinary system benign neoplasm located_in the bladder including papillomas, leiomyomas, fibromas, hemangiomas, neurofibromas and lipomas." [url:https\://www.ncbi.nlm.nih.gov/pmc/articles/PMC1398414/]
[doid]:   5%|▍         | 663/14.5k [00:00<00:08, 1.68kit/s]WARNING:pyobo.struct.obo.reader:[doid:0050657] unregistered prefix in SNOMEDCT_US_2025_03_01:716862002 in xref
WARNING:pyobo.struct.obo.reader:[doid:0050657] unregistered prefix in SNOMEDCT_US_2025_03_01:763867001 in xref
WARNING:pyobo.struct.obo.reader:[doid:0050657] unregistered prefix in SNOMEDCT_US_2025_05_01:722859001 in xref
WARNING:pyobo.struct.obo.reader:[doid:0050663] unregistered prefix in SNOMEDCT_US_2025_09_01:718572004 in xref
WARNING:pyobo.struct.reference:[doid:0050678] failed Pydantic validation http://www.omim.org/entry/186580?search=186580&highlight=186580 in definition provenance in "A syndrome characterized by familial granulomatous arthritis, uveitis and skin granulomas. It has_material_basis_in heterozygous mutations in the NOD2 gene." [url:http\://en.wikipedia.org/wiki/Blau_syndrome, url:http\://www.omim.org/entry/186580?search=186580&highlight=186580]
WARNING:pyobo.struct.reference:[doid:0050701] failed Pydantic validation http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3267655/table/T1 in definition provenance in "An epilepsy syndrome that is a group of clinical entities showing a cluster of electro-clinical characteristics, classified according to age at onset, cognitive and developmental antecedents and consequences, motor and sensory examinations, EEG features, provoking or triggering factors, and patterns of seizure occurrence with respect to sleep." [url:http\://www.ice-epilepsy.org/new-ice-terminology-from-ilae.html, url:http\://www.ncbi.nlm.nih.gov/pmc/articles/PMC3267655/table/T1/, url:https\://www.ncbi.nlm.nih.gov/pubmed/20196795]
WARNING:pyobo.struct.reference:[doid:0050706] failed Pydantic validation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3267655 in definition provenance in "An electroclinial syndrome that is characterized by development of seizures later in life with a variable age of onset and duration." [url:https\://www.ncbi.nlm.nih.gov/pmc/articles/PMC3267655/]
WARNING:pyobo.struct.reference:[doid:0050711] failed Pydantic validation http://omim.org/entry/604290?search=604290&highlight=604290 in definition provenance in "An iron metabolism disease that has_material_basis_in a mutation in the ceruloplasmin gene characterized by progressive neurodegeneration of the retina and basal ganglia and diabetes mellitus." [url:http\://en.wikipedia.org/wiki/Aceruloplasminemia, url:http\://omim.org/entry/604290?search=604290&highlight=604290]
WARNING:pyobo.struct.reference:[doid:0050715] failed Pydantic validation http://omim.org/entry/277400?search=METHYLMALONIC%20ACIDURIA&highlight=methylmalonic%20aciduria%20%22methylmalonic%20aciduria%22 in definition provenance in "A methylmalonic acidemia that has_material_basis_in deficiency in synthesis of both AdoCbl and MeCbl (cblC) and is characterized by decreased levels of the coenzymes adenosylcobalamin (AdoCbl) and methylcobalamin (MeCbl), which results in decreased activity of the respective enzymes methylmalonyl-CoA mutase." [url:http\://omim.org/entry/277400?search=METHYLMALONIC%20ACIDURIA&highlight=methylmalonic%20aciduria%20%22methylmalonic%20aciduria%22]
WARNING:pyobo.struct.reference:[doid:0050716] failed Pydantic validation http://omim.org/entry/277410?search=METHYLMALONIC%20ACIDURIA&highlight=methylmalonic%20aciduria%20%22methylmalonic%20aciduria%22 in definition provenance in "A methylmalonic aciduria that is characterized by combined homocystinuria and methylmalonic aciduria and deficiency of MCM and MS activities." [url:http\://omim.org/entry/277410?search=METHYLMALONIC%20ACIDURIA&highlight=methylmalonic%20aciduria%20%22methylmalonic%20aciduria%22, url:https\://www.ncbi.nlm.nih.gov/pubmed/18385497]
WARNING:pyobo.struct.reference:[doid:0050723] failed Pydantic validation http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1852735 in definition provenance in "A serine deficiency that has_material_basis_in deficiency of phosphoserine aminotransferase and is characterized by low concentartions of serine and flycine in plasma and cerebrospinal fluid." [url:http\://www.ncbi.nlm.nih.gov/pmc/articles/PMC1852735/, url:http\://www.omim.org/entry/610992?search=610992&highlight=610992, url:http\://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=284417]
WARNING:pyobo.struct.reference:[doid:0050723] failed Pydantic validation http://www.omim.org/entry/610992?search=610992&highlight=610992 in definition provenance in "A serine deficiency that has_material_basis_in deficiency of phosphoserine aminotransferase and is characterized by low concentartions of serine and flycine in plasma and cerebrospinal fluid." [url:http\://www.ncbi.nlm.nih.gov/pmc/articles/PMC1852735/, url:http\://www.omim.org/entry/610992?search=610992&highlight=610992, url:http\://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=284417]
WARNING:pyobo.struct.reference:[doid:0050725] failed Pydantic validation http://www.omim.org/entry/276600?search=276600&highlight=276600 in definition provenance in "A tyrosinemia that has_material_basis_in deficiency of hepatic tyrosine aminotransferase located_in the liver and is characterized by keratitis, painful palmoplantar hyperkeratosis, mental retardation, and elevated serum tyrosine levels." [url:http\://en.wikipedia.org/wiki/Tyrosinemia_type_II, url:http\://www.omim.org/entry/276600?search=276600&highlight=276600]
WARNING:pyobo.struct.reference:[doid:0050727] failed Pydantic validation http://www.omim.org/entry/276710?search=tyrosinemia&highlight=tyrosinemia in definition provenance in "A tyrosinemia that has_material_basis_in deficiency of 4-hydroxyphenylpyruvate dioxygenase disrupting the break down of tyrosine." [url:http\://en.wikipedia.org/wiki/Type_III_tyrosinemia, url:http\://www.omim.org/entry/276710?search=tyrosinemia&highlight=tyrosinemia]
WARNING:pyobo.struct.reference:[doid:0050734] failed Pydantic validation http://omim.org/entry/261000?search=261000&highlight=261000 in definition provenance in "A vitamin B12 deficiency that is characterized by megaloblastic anemia due to the absence of gastric intrinsic factor which results in abnormal vitamin B12 absorption." [url:http\://omim.org/entry/261000?search=261000&highlight=261000, url:http\://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=332, url:https\://www.ncbi.nlm.nih.gov/pubmed/14695536]
WARNING:pyobo.struct.obo.reader:[doid:0050741] failed Pydantic validation KEGG:05034 in xref
WARNING:pyobo.struct.obo.reader:[doid:0050745] failed Pydantic validation ICD11:2A81.Z in xref
WARNING:pyobo.struct.reference:[doid:0050777] failed Pydantic validation http://omim.org/entry/213300?search=joubert&highlight=joubert in definition provenance in "A ciliopathy that is characterized by congenital malformation of the brainstem and agenesis or hypoplasia of the cerebellar vermis leading to an abnormal respiratory pattern, nystagmus, hypotonia, ataxia, and delay in achieving motor milestones." [url:http\://en.wikipedia.org/wiki/Joubert_syndrome, url:http\://omim.org/entry/213300?search=joubert&highlight=joubert]
WARNING:pyobo.struct.reference:[doid:0050779] failed Pydantic validation http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1017280/?page=1 in definition provenance in "A syndrome characterized by multiple fetal developmental defects including polydactyly and central nervous system malformations that results from a single amino acid mutation of D211G of the HYLS1 gene which plays a central role in cilia formation." [url:http\://www.ncbi.nlm.nih.gov/pmc/articles/PMC1017280/?page=1, url:http\://www.ncbi.nlm.nih.gov/pmc/articles/PMC2751977/#B33, url:https\://www.ncbi.nlm.nih.gov/pubmed/15843405]
WARNING:pyobo.struct.reference:[doid:0050779] failed Pydantic validation http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2751977/#B33 in definition provenance in "A syndrome characterized by multiple fetal developmental defects including polydactyly and central nervous system malformations that results from a single amino acid mutation of D211G of the HYLS1 gene which plays a central role in cilia formation." [url:http\://www.ncbi.nlm.nih.gov/pmc/articles/PMC1017280/?page=1, url:http\://www.ncbi.nlm.nih.gov/pmc/articles/PMC2751977/#B33, url:https\://www.ncbi.nlm.nih.gov/pubmed/15843405]
WARNING:pyobo.struct.reference:[doid:0050780] failed Pydantic validation http://www.genome.jp/dbget-bin/www_bget?ds\:H00583 in definition provenance in "A syndrome that is characterized by hypertelorism, hypospadias, and additional midline defects." [url:http\://www.genome.jp/dbget-bin/www_bget?ds\:H00583, url:http\://www.ncbi.nlm.nih.gov/books/NBK1327/, url:http\://www.ncbi.nlm.nih.gov/books/NBK1523/, url:https\://ghr.nlm.nih.gov/condition/opitz-g-bbb-syndrome]
WARNING:pyobo.struct.reference:[doid:0050791] failed Pydantic validation http://omim.org/entry/261550?search=261550&highlight=261550 in definition provenance in "A pseudohermaphroditism that is characterized by the persistence of Mullerian duct derivatives (i.e. uterus, cervix, fallopian tubes and upper two thirds of vagina) in a phenotypically and karyotypically male." [url:http\://ghr.nlm.nih.gov/condition/persistent-mullerian-duct-syndrome, url:http\://omim.org/entry/261550?search=261550&highlight=261550, url:http\://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=2856, url:https\://www.ncbi.nlm.nih.gov/pubmed/20352001]
WARNING:pyobo.struct.reference:[doid:0050792] failed Pydantic validation http://omim.org/entry/600195?search=600195&highlight=600195 in definition provenance in "A vein disease that is characterized by multiple bluish cutaneous or mucosal venous lesions that has_material_basis_in heterozygous mutation in the TEK gene on chromosome 9p21." [url:http\://omim.org/entry/600195?search=600195&highlight=600195, url:https\://medlineplus.gov/genetics/condition/multiple-cutaneous-and-mucosal-venous-malformations/, url:https\://www.ncbi.nlm.nih.gov/pubmed/20301733]
WARNING:pyobo.struct.reference:[doid:0050793] failed Pydantic validation http://omim.org/entry/609620?search=SHORT%20QT%20SYNDROME&highlight=syndromic%20short%20qt%20syndrome in definition provenance in "A heart conduction disease that is characterized by heart arrhythmia defined as a short QT interval on an EKG (less than 300 ms) that does not significantly change with heart rate, tall and peaked T waves, and a structurally normal heart." [url:http\://en.wikipedia.org/wiki/Short_QT_syndrome, url:http\://ghr.nlm.nih.gov/condition/short-qt-syndrome, url:http\://omim.org/entry/609620?search=SHORT%20QT%20SYNDROME&highlight=syndromic%20short%20qt%20syndrome, url:http\://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=51083]
WARNING:pyobo.struct.reference:[doid:0050794] failed Pydantic validation http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2706969 in definition provenance in "A dysostosis that is characterized by characterized by multiple joint fusions, usually commencing in the hands, conductive deafness, and characteristic facial features, including a broad, tubular-shaped nose and a thin upper vermilion." [url:http\://www.ncbi.nlm.nih.gov/pmc/articles/PMC2706969/]
WARNING:pyobo.struct.reference:[doid:0050807] failed Pydantic validation http://omim.org/entry/612713?search=Kahrizi%20syndrome&highlight=syndromic%20kahrizi%20syndrome in definition provenance in "A syndrome that is characterized by mental retardation, cataracts, coloboma, kyphosis, and coarse facial features and has_material_basis_in mutation in the SRD5A3 gene." [url:http\://omim.org/entry/612713?search=Kahrizi%20syndrome&highlight=syndromic%20kahrizi%20syndrome, url:http\://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=168972]
[doid]:   6%|▌         | 844/14.5k [00:00<00:09, 1.38kit/s]WARNING:pyobo.struct.reference:[doid:0050811] failed Pydantic validation http://www.genome.jp/dbget-bin/www_bget?ds\:H00216 in definition provenance in "A steroid inherited metabolic disorder that is characterized by adrenal insufficiency and variable degrees of hyper or hypo androgyny manifestations resulting from steroidogenic enzyme deficiency." [url:http\://omim.org/entry/201710, url:http\://www.genome.jp/dbget-bin/www_bget?ds\:H00216, url:http\://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=GB&Expert=418.0]
WARNING:pyobo.struct.reference:[doid:0050826] failed Pydantic validation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5494422 in definition provenance in "A heart valve disease that is characterized by valvular insufficiency or valvular stenosis, located_in tricuspid valve between the right atrium and right ventricle." [url:https\://www.ncbi.nlm.nih.gov/pmc/articles/PMC5494422/]
WARNING:pyobo.struct.reference:[doid:0050847] failed Pydantic validation http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2765300 in definition provenance in "A sleep disorder characterized by repeated cessation and commencing of breathing that repeatedly disrupts sleep." [url:http\://www.mayoclinic.org/diseases-conditions/sleep-apnea/basics/definition/con-20020286, url:http\://www.ncbi.nlm.nih.gov/pmc/articles/PMC2765300/, url:http\://www.nhlbi.nih.gov/health/health-topics/topics/sleepapnea/]
WARNING:pyobo.struct.reference:[doid:0050848] failed Pydantic validation https://www.ncbi.nlm.nih.gov/books/NBK63555/#executivesummary.s1 in definition provenance in "A sleep apnea that is characterized by repeated collapse and obstruction of the upper airway during sleep, which results in reduced airflow (hypopnea) or complete airflow cessation (apnea), oxygen desaturation, and arousals from sleep." [url:http\://en.wikipedia.org/wiki/Obstructive_sleep_apnea, url:http\://www.mayoclinic.org/diseases-conditions/sleep-apnea/basics/definition/con-20020286, url:http\://www.nlm.nih.gov/medlineplus/ency/article/000811.htm, url:https\://www.ncbi.nlm.nih.gov/books/NBK63555/#executivesummary.s1]
WARNING:pyobo.struct.reference:[doid:0050849] failed Pydantic validation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3244941 in definition provenance in "An ampulla of Vater neoplasm that is characterized by glandular dysplastic lesion having pre-malignant potential." [url:https\://www.ncbi.nlm.nih.gov/pmc/articles/PMC3244941/]
WARNING:pyobo.struct.reference:[doid:0050855] failed Pydantic validation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2776335 in definition provenance in "A kidney disease that is characterized by progressive detrimental connective tissue deposition of the kidney parenchyma leading to deterioration of renal function." [url:https\://www.ncbi.nlm.nih.gov/pmc/articles/PMC2776335/]

[doid 2026-02-28] writing names to /home/agar/.data/pyobo/raw/doid/2026-02-28/cache/names.tsv.gz
[doid 2026-02-28] writing definitions to /home/agar/.data/pyobo/raw/doid/2026-02-28/cache/definitions.tsv.gz
[doid 2026-02-28] writing species to /home/agar/.data/pyobo/raw/doid/2026-02-28/cache/species.tsv.gz
[doid 2026-02-28] writing alts to /home/agar/.data/pyobo/raw/doid/2026-02-28/cache/alt_ids.tsv.gz
[doid 2026-02-28] writing mappings to /home/agar/.data/pyobo/raw/doid/2026-02-28/cache/mappings.tsv.gz

WARNING:pyobo.struct.struct:[doid:0050524] undefined typedef: ReferenceTuple(prefix='obo', identifier='doid#relatedMatch')
WARNING:pyobo.struct.struct:[doid:0050657] undefined typedef: ReferenceTuple(prefix='obo', identifier='doid#closeMatch')

[doid 2026-02-28] writing relations to /home/agar/.data/pyobo/raw/doid/2026-02-28/cache/relations.tsv.gz
[doid 2026-02-28] writing edges to /home/agar/.data/pyobo/raw/doid/2026-02-28/cache/edges.tsv.gz
[doid 2026-02-28] writing object_properties to /home/agar/.data/pyobo/raw/doid/2026-02-28/cache/object_properties.tsv.gz
[doid 2026-02-28] writing literal_properties to /home/agar/.data/pyobo/raw/doid/2026-02-28/cache/literal_properties.tsv.gz
[doid 2026-02-28] writing literal_mappings to /home/agar/.data/pyobo/raw/doid/2026-02-28/cache/literal_mappings.tsv.gz

In [3]:
# Test

mondo_grounder.ground_df(df, "Category", target_column=f"Category_mondo_curie")
uberon_grounder.ground_df(df, "Category", target_column=f"Category_uberon_curie")
cl_grounder.ground_df(df, "Category", target_column=f"Category_cl_curie")
doid_grounder.ground_df(df, "Category", target_column=f"Category_doid_curie")

mondo_grounder.ground_df(df, "Category", target_column=f"Category_mondo_reference", target_type="reference")
uberon_grounder.ground_df(df, "Category", target_column=f"Category_uberon_reference", target_type="reference")
cl_grounder.ground_df(df, "Category", target_column=f"Category_cl_reference", target_type="reference")
doid_grounder.ground_df(df, "Category", target_column=f"Category_doid_reference", target_type="reference")

df

,Category,Evidence,Quality,autoimmune,Parent,Disease,Syn,SNOMED,ConceptID,Profile,...,Rose_Mackay Citation,Pubmed Evidence (incomplete),Category_mondo_curie,Category_uberon_curie,Category_cl_curie,Category_doid_curie,Category_mondo_reference,Category_uberon_reference,Category_cl_reference,Category_doid_reference
0,Skin,Antibody,Moderate,Autoimmune,Acquired epidermolysis bullosa,Acquired epidermolysis bullosa,N,2772003.0,4100661.0,In epidermolysis bullosa acquisita (EBA) the s...,...,Epidermolysis bullosa acquisita (EBA) is an ac...,NaN,mondo:0002531,uberon:0000014,None,None,prefix='mondo' identifier='0002531' name='skin...,prefix='uberon' identifier='0000014' name='zon...,None,None
1,Skin,Antibody,Moderate,Autoimmune,Acquired epidermolysis bullosa,EBA,A,2772003.0,NaN,NaN,...,NaN,NaN,mondo:0002531,uberon:0000014,None,None,prefix='mondo' identifier='0002531' name='skin...,prefix='uberon' identifier='0000014' name='zon...,None,None
2,Skin,Antibody,Moderate,Autoimmune,Acquired epidermolysis bullosa,Autoimmune epidermolysis bullosa,S,2772003.0,NaN,NaN,...,NaN,NaN,mondo:0002531,uberon:0000014,None,None,prefix='mondo' identifier='0002531' name='skin...,prefix='uberon' identifier='0000014' name='zon...,None,None
3,Skin,Antibody,Moderate,Autoimmune,Acquired epidermolysis bullosa,Epidermolysis bullosa acquisita,S,2772003.0,NaN,NaN,...,NaN,NaN,mondo:0002531,uberon:0000014,None,None,prefix='mondo' identifier='0002531' name='skin...,prefix='uberon' identifier='0000014' name='zon...,None,None
4,Blood,Antibody,Moderate,Autoimmune,Acquired hemophilia,Acquired hemophilia,N,785308008.0,37203917.0,Acquired Hemophilia is an autoimmune disorder ...,...,In addition to marking cells for ADCC or phago...,https://pubmed.ncbi.nlm.nih.gov/?term=Acquired...,None,uberon:0000178,None,None,None,prefix='uberon' identifier='0000178' name='blood',None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,None,None,None,None
708,"© 2026 Autoimmune Registry, Inc.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,None,None,None,None
709,This work is licensed under the Creative Commo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,None,None,None,None
710,"You are free to share and adapt this material,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,None,None,None,None
711,License: https://creativecommons.org/licenses/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,None,None,None,None

In [ ]:
def create_link(curie):

    # Examples    
    # https://www.ebi.ac.uk/ols4/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0110751
    # https://www.ebi.ac.uk/ols4/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13378
    # https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000178
    
    curie_split = curie.split(':')
    ns = curie_split[0]
    id = curie_split[1]
    return f"https://www.ebi.ac.uk/ols/ontologies/{ns.lower()}/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252F{ns}_{id}"

In [ ]:
create_link("UBERON:0000178")

'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000178'

In [231]:
def create_link(curie):

    # Examples    
    # https://www.ebi.ac.uk/ols4/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0110751
    # https://www.ebi.ac.uk/ols4/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13378
    # https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000178
    
    curie_split = curie.split(':')
    ns = curie_split[0]
    id = curie_split[1]
    return f"https://www.ebi.ac.uk/ols/ontologies/{ns.lower()}/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252F{ns}_{id}"
    
def ground_column(df, column, grounder, target_type="curie"):
    grounder.ground_df(df, column, target_column=f"{column}_reference", target_type="reference")

    if "curie" in target_type:
        grounder.ground_df(df, column, target_column=f"{column}_curie", target_type="curie")
        
        df[f"{column}_curie"] = df[f"{column}_curie"].apply(
            lambda x: x if pd.isna(x) else (x.upper() if ':' not in x else x.split(':')[0].upper() + ':' + x.split(':')[1])
        )
        
        # Add link
        df[f"{column}_link"] = df[f"{column}_curie"].apply(
            lambda x: create_link(x) if x and ':' in x else None
        ) 
        
        df[f"{column}_curie"] = df[f"{column}_curie"].apply(
            lambda x: f"{x.split(':')[0]}:{x.split(':')[1].zfill(7)}" if x and ':' in x else x
        )

        
    if "name" in target_type:
        df[f"{column}_name"] = df[f"{column}_reference"].apply(lambda x: x.name if x else None)
    return df[[ column ] + [ f"{column}_{t}" for t in target_type ] + [ f"{column}_link" ] if "curie" in target_type else [] ]

In [232]:
a_df = df[["Category", "Disease"]][:-6]
a_ground_df = ground_column(a_df, "Disease", doid_grounder, target_type=["curie", "name"])
a_ground_df

,Disease,Disease_curie,Disease_name,Disease_link
0,Acquired epidermolysis bullosa,DOID:0004313,epidermolysis bullosa acquisita,https://www.ebi.ac.uk/ols/ontologies/doid/clas...
1,EBA,None,None,None
2,Autoimmune epidermolysis bullosa,None,None,None
3,Epidermolysis bullosa acquisita,DOID:0004313,epidermolysis bullosa acquisita,https://www.ebi.ac.uk/ols/ontologies/doid/clas...
4,Acquired hemophilia,None,None,None
...,...,...,...,...
701,Warm autoimmune hemolytic anemia,None,None,None
702,Acquired autoimmune hemolytic anemia,None,None,None
703,Idiopathic autoimmune hemolytic anemia,None,None,None
704,Immune hemolytic anemia,None,None,None
705,Immunohemolytic anemia,None,None,None

In [233]:
list(a_ground_df["Disease_link"])

['https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_4313',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_4313',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_10992',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_10992',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_639',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_639',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13378',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13378',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13378',
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13774',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_10493',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_14256',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_10871',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_986',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0050634',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0111157',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0111157',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_7147',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_9808',
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_9808',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_9808',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_9808',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_3049',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_12132',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_2988',
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0080744',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_12449',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_417',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_9849',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_2361',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13382',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13381',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0040090',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8929',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_4030',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_718',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_2048',
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_6688',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_6688',
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0040091',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0111079',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0111079',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_7188',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_7188',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_7188',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_7188',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_7188',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_7188',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_7188',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0080749',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0080747',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0060220',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0040097',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0060215',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_10588',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0060215',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13241',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13241',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13241',
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_11656',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_11656',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_11656',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8506',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8506',
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_10608',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_10608',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_10608',
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8544',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8544',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_5213',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_2536',
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_1678',
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_11729',
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_11729',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0060645',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0080848',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0060216',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13353',
 None,
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_3223',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_3222',
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_1811',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8778',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0060192',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0060191',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0060190',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0060188',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0050157',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_2797',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0050169',
 None,
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_3663',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8505',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8505',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_14203',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_10223',
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_9744',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0050214',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0050214',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0050214',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0050214',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_289',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_288',
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13922',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_1826',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0080750',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_11042',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_11042',
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_631',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_7997',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_12361',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_12361',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_10719',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_12889',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_12889',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_12842',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_12842',
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_14482',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_14482',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_2280',
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_9809',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0050156',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_2986',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_1587',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8924',
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8924',
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_11123',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_11123',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_11123',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_11123',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0080356',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_3429',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8778',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0050589',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0060182',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8577',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_12731',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_12732',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_12732',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_12732',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0050157',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0050156',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_3082',
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_676',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_676',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_9201',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13477',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_3928',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0060182',
 None,
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_3492',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_3492',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_10439',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8463',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8472',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_8472',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13099',
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13099',
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13099',
 None,
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_2377',
 None,
 None,

In [237]:
for col in ["Category"]:
    # build the single column dataframe
    df_x = pd.DataFrame(df[col][:-6].unique(), columns=[col])

    for ns in ["uberon"]:
        # ground with target_type
        df_x = ground_column(df_x, col, globals()[f"{ns}_grounder"], target_type=["curie", "name"])
    
    # Write out the results for each column and each namespace in CSV file
    with open(f"{col}-{ns}.csv", "w") as file:
        df_x.to_csv(file, index=False)

df_x

,Category,Category_curie,Category_name,Category_link
0,Skin,UBERON:0000014,zone of skin,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...
1,Blood,UBERON:0000178,blood,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...
2,Nervous System,UBERON:0001016,nervous system,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...
3,Vascular system,UBERON:0007798,vascular system,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...
4,Glands,UBERON:0002530,gland,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...
5,Systemic,None,None,None
6,Musculoskeletal,None,None,None
7,Kidney,UBERON:0002113,kidney,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...
8,All,UBERON:0014899,anterolateral ligament of knee,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...
9,Digestive system,UBERON:0001007,digestive system,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...
10,Liver,UBERON:0002107,liver,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...
11,Pancreas,UBERON:0001264,pancreas,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...
12,Bladder,UBERON:0001255,urinary bladder,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...
13,Lungs,UBERON:0002048,lung,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...
14,Heart,UBERON:0000948,heart,https://www.ebi.ac.uk/ols/ontologies/uberon/cl...

In [240]:
list(df_x["Category_link"])

['https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000014',
 'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000178',
 'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001016',
 'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0007798',
 'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0002530',
 None,
 None,
 'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0002113',
 'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0014899',
 'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001007',
 'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0002107',
 'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001264',
 'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001255',
 'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0002048',
 'https://www.ebi.ac.uk/ols/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000948']

In [180]:
for col in ["Parent","Disease"]:
    # build the single column dataframe
    df_x = pd.DataFrame(df[col][:-4].unique(), columns=[col])

    for ns in ["doid"]:     #FIXME Multiple ns are overwritten due to same col name, prefer to append curies instead of adding columns(?)
        # ground with label
        df_x = ground_column(df_x, col, globals()[f"{ns}_grounder"], ["curie", "name"])
    
print(df_x)

                                    Disease Disease_curie  \
0            Acquired epidermolysis bullosa  doid:0004313
1                                       EBA          None
2          Autoimmune epidermolysis bullosa          None
3           Epidermolysis bullosa acquisita  doid:0004313
4                       Acquired hemophilia          None
..                                      ...           ...
690    Acquired autoimmune hemolytic anemia          None
691  Idiopathic autoimmune hemolytic anemia          None
692                 Immune hemolytic anemia          None
693                  Immunohemolytic anemia          None
694                                     NaN          None

                        Disease_name
0    epidermolysis bullosa acquisita
1                               None
2                               None
3    epidermolysis bullosa acquisita
4                               None
..                               ...
690                             None
691                             None
692                             None
693                             None
694                             None

[695 rows x 3 columns]

In [241]:
# Version 1.2 - added name grounding and fixed the target column names to be consistent across namespaces

def create_link(curie):

    # Examples    
    # https://www.ebi.ac.uk/ols4/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_0110751
    # https://www.ebi.ac.uk/ols4/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_13378
    # https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000178
    
    curie_split = curie.split(':')
    ns = curie_split[0]
    id = curie_split[1]
    return f"https://www.ebi.ac.uk/ols/ontologies/{ns.lower()}/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252F{ns}_{id}"
    
def ground_column(df, column, grounder, target_type="curie"):
    grounder.ground_df(df, column, target_column=f"{column}_reference", target_type="reference")

    if "curie" in target_type:
        grounder.ground_df(df, column, target_column=f"{column}_curie", target_type="curie")
        
        df[f"{column}_curie"] = df[f"{column}_curie"].apply(
            lambda x: x if pd.isna(x) else (x.upper() if ':' not in x else x.split(':')[0].upper() + ':' + x.split(':')[1])
        )
        
        # Add link
        df[f"{column}_link"] = df[f"{column}_curie"].apply(
            lambda x: create_link(x) if x and ':' in x else None
        ) 
        
        df[f"{column}_curie"] = df[f"{column}_curie"].apply(
            lambda x: f"{x.split(':')[0]}:{x.split(':')[1].zfill(7)}" if x and ':' in x else x
        )

        
    if "name" in target_type:
        df[f"{column}_name"] = df[f"{column}_reference"].apply(lambda x: x.name if x else None)
    return df[[ column ] + [ f"{column}_{t}" for t in target_type ] + [ f"{column}_link" ] if "curie" in target_type else [] ]
for col in ["Category"]:
    # build the single column dataframe
    df_x = pd.DataFrame(df[col][:-6].unique(), columns=[col])

    for ns in ["uberon"]:
        # ground with reference
        df_x = ground_column(df_x, col, globals()[f"{ns}_grounder"], target_type=["curie", "name"])
    
    # Write out the results for each column and each namespace in CSV file
    with open(f"{col}_{ns}_grounded.csv", "w") as file:
        df_x.to_csv(file, index=False)

for col in ["Parent","Disease"]:
    # build the single column dataframe
    df_x = pd.DataFrame(df[col][:-6].unique(), columns=[col])

    for ns in ["doid"]:
        # ground with reference
        df_x = ground_column(df_x, col, globals()[f"{ns}_grounder"], ["curie", "name"])
    
    # Write out the results for each column and each namespace in CSV file
    with open(f"{col}_{ns}_grounded.csv", "w") as file:
        df_x.to_csv(file, index=False)

---

### Test grounds

In [8]:
mondo_grounder.ground_df(df, "Category", target_column=f"Category_mondo_curie")
uberon_grounder.ground_df(df, "Category", target_column=f"Category_uberon_curie")
cl_grounder.ground_df(df, "Category", target_column=f"Category_cl_curie")
doid_grounder.ground_df(df, "Category", target_column=f"Category_doid_curie")

mondo_grounder.ground_df(df, "Evidence", target_column=f"Evidence_mondo_curie")
uberon_grounder.ground_df(df, "Evidence", target_column=f"Evidence_uberon_curie")
cl_grounder.ground_df(df, "Evidence", target_column=f"Evidence_cl_curie")
doid_grounder.ground_df(df, "Evidence", target_column=f"Evidence_doid_curie")

mondo_grounder.ground_df(df, "Parent", target_column=f"Parent_mondo_curie")
uberon_grounder.ground_df(df, "Parent", target_column=f"Parent_uberon_curie")
cl_grounder.ground_df(df, "Parent", target_column=f"Parent_cl_curie")
doid_grounder.ground_df(df, "Parent", target_column=f"Parent_doid_curie")

mondo_grounder.ground_df(df, "Disease", target_column=f"Disease_mondo_curie")
uberon_grounder.ground_df(df, "Disease", target_column=f"Disease_uberon_curie")
cl_grounder.ground_df(df, "Disease", target_column=f"Disease_cl_curie")
doid_grounder.ground_df(df, "Disease", target_column=f"Disease_doid_curie")

In [9]:
mondo_grounder.ground_df(df, "Category", target_column=f"Category_mondo_reference", target_type="reference")
uberon_grounder.ground_df(df, "Category", target_column=f"Category_uberon_reference", target_type="reference")
cl_grounder.ground_df(df, "Category", target_column=f"Category_cl_reference", target_type="reference")
doid_grounder.ground_df(df, "Category", target_column=f"Category_doid_reference", target_type="reference")

mondo_grounder.ground_df(df, "Evidence", target_column=f"Evidence_mondo_reference", target_type="reference")
uberon_grounder.ground_df(df, "Evidence", target_column=f"Evidence_uberon_reference", target_type="reference")
cl_grounder.ground_df(df, "Evidence", target_column=f"Evidence_cl_reference", target_type="reference")
doid_grounder.ground_df(df, "Evidence", target_column=f"Evidence_doid_reference", target_type="reference")

mondo_grounder.ground_df(df, "Parent", target_column=f"Parent_mondo_reference", target_type="reference")
uberon_grounder.ground_df(df, "Parent", target_column=f"Parent_uberon_reference", target_type="reference")
cl_grounder.ground_df(df, "Parent", target_column=f"Parent_cl_reference", target_type="reference")
doid_grounder.ground_df(df, "Parent", target_column=f"Parent_doid_reference", target_type="reference")

mondo_grounder.ground_df(df, "Disease", target_column=f"Disease_mondo_reference", target_type="reference")
uberon_grounder.ground_df(df, "Disease", target_column=f"Disease_uberon_reference", target_type="reference")
cl_grounder.ground_df(df, "Disease", target_column=f"Disease_cl_reference", target_type="reference")
doid_grounder.ground_df(df, "Disease", target_column=f"Disease_doid_reference", target_type="reference")

In [10]:
for col in ["Category","Evidence","Parent","Disease"]:
    # for the Bioregistry-standardized CURIEs
    mondo_grounder.ground_df(df, col, target_column=f"{col}_mondo_curie")
    uberon_grounder.ground_df(df, col, target_column=f"{col}_uberon_curie")
    cl_grounder.ground_df(df, col, target_column=f"{col}_cl_curie")
    doid_grounder.ground_df(df, col, target_column=f"{col}_doid_curie")

    # for Bioregistry-standardized references (e.g., pre-parsed prefix, identifier, and name)
    mondo_grounder.ground_df(
        df, col, target_column=f"{col}_mondo_reference", target_type="reference"
    )
    uberon_grounder.ground_df(
        df, col, target_column=f"{col}_uberon_reference", target_type="reference"
    )
    cl_grounder.ground_df(
        df, col, target_column=f"{col}_cl_reference", target_type="reference"
    )
    doid_grounder.ground_df(
        df, col, target_column=f"{col}_doid_reference", target_type="reference"
    )

#TODO for SNOMED id, get the name from the SNOMED CT ontology and ground that instead of the raw SNOMED id

In [ ]:
# # this adds a new column `organ_curie` that has strings
# # for the Bioregistry-standardized CURIEs
# mondo_grounder.ground_df(df, "term", target_column="term_curie")
# uberon_grounder.ground_df(df, "term", target_column="uberon_curie")
# cl_grounder.ground_df(df, "term", target_column="cl_curie")
# doid_grounder.ground_df(df, "term", target_column="doid_curie")

# # this adds a new column `organ_reference` that has reference objects
# # for Bioregistry-standardized references (e.g., pre-parsed prefix, identifier, and name)
# mondo_grounder.ground_df(
#     df, "term", target_column="mondo_reference", target_type="reference"
# )
# uberon_grounder.ground_df(
#     df, "term", target_column="uberon_reference", target_type="reference"
# )
# cl_grounder.ground_df(
#     df, "term", target_column="cl_reference", target_type="reference"
# )
# doid_grounder.ground_df(
#     df, "term", target_column="doid_reference", target_type="reference"
# )

In [11]:
cols_all = [
    "Category", *[f"Category_{col}_curie" for col in ["mondo", "uberon", "cl", "doid"]], *[f"Category_{col}_reference" for col in ["mondo", "uberon", "cl", "doid"]],
    "Evidence", *[f"Evidence_{col}_curie" for col in ["mondo", "uberon", "cl", "doid"]], *[f"Evidence_{col}_reference" for col in ["mondo", "uberon", "cl", "doid"]],
    "Quality","autoimmune",
    "Parent", *[f"Parent_{col}_curie" for col in ["mondo", "uberon", "cl", "doid"]], *[f"Parent_{col}_reference" for col in ["mondo", "uberon", "cl", "doid"]],
    "Disease",  *[f"Disease_{col}_curie" for col in ["mondo", "uberon", "cl", "doid"]], *[f"Disease_{col}_reference" for col in ["mondo", "uberon", "cl", "doid"]],
    "Syn","SNOMED","ConceptID"]

In [13]:
# # print the final dataframe to show below
# print(df.to_markdown(tablefmt="rst", index=False))
df.to_csv("../ARI List of Autoimmune Diseases 2026-grounded.csv", index = False)

In [4]:
import inspect
import ssslm

source = inspect.getsource(ssslm.Grounder)
location = inspect.getfile(ssslm.Grounder)

print(f"File: {location}")
print("-" * 20)
print(source)

File: /home/agar/.venvs/biomap_venv/lib/python3.12/site-packages/ssslm/ner.py
--------------------
class Grounder(Matcher, Annotator, ABC):
    """A combine matcher and annotator."""

---

### Source test

In [134]:
data_url = "https://raw.githubusercontent.com/OBOAcademy/obook/master/docs/tutorial/linking_data/data.csv"
df = pd.read_csv(data_url)
df = df[["species", "strain", "organ"]]

# this adds a new column `organ_curie` that has strings
# for the Bioregistry-standardized CURIEs
uberon_grounder.ground_df(df, "organ", target_column="organ_curie")

# this adds a new column `organ_reference` that has reference objects
# for Bioregistry-standardized references (e.g., pre-parsed prefix, identifier, and name)
uberon_grounder.ground_df(
    df, "organ", target_column="organ_reference", target_type="reference"
)

# print the final dataframe to show below
print(df.to_markdown(tablefmt="rst", index=False))

=========  ========  ==============  ==============  ==========================================================
species    strain    organ           organ_curie     organ_reference
=========  ========  ==============  ==============  ==========================================================
RAT        F 344/N   LUNG            uberon:0002048  prefix='uberon' identifier='0002048' name='lung'
MOUSE      B6C3F1    NOSE            uberon:0000004  prefix='uberon' identifier='0000004' name='nose'
RAT        F 344/N   ADRENAL CORTEX  uberon:0001235  prefix='uberon' identifier='0001235' name='adrenal cortex'
=========  ========  ==============  ==============  ==========================================================

---

In [143]:
col = "Category"
df[col][:-4].unique()

array(['Skin', 'Blood', 'Nervous System', 'Vascular system', 'Glands',
       'Systemic', 'Musculoskeletal', 'Kidney', 'All', 'Digestive system',
       'Liver', 'Pancreas', 'Bladder', 'Lungs', 'Heart', nan],
      dtype=object)

In [150]:
for item in df[col][:-4].unique():
    if item != item:  # check for NaN
        continue
    print(item)
    grounder.get_best_match(item)

Skin
Blood
Nervous System
Vascular system
Glands
Systemic
Musculoskeletal
Kidney
All
Digestive system
Liver
Pancreas
Bladder
Lungs
Heart

---

In [1]:
import biomappings
import inspect

# Let's find out how it loads true mappings
source = inspect.getsource(biomappings.load_mappings)
location = inspect.getfile(biomappings.load_mappings)

print(f"File: {location}")
print("-" * 20)
print(source)

ModuleNotFoundError: No module named 'biomappings'